configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkProgressTrackerTesting/
        - Sources/SparkProgressTrackerSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkProgressTrackerTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkProgressTracker]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkProgressTrackerTesting/
        - Sources/SparkProgressTrackerSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkProgressTrackerTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkProgressTracker]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkProgressTrackerTesting/
        - Sources/SparkProgressTrackerSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkProgressTrackerTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkProgressTracker]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkProgressTrackerTesting/
        - Sources/SparkProgressTrackerSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkProgressTrackerTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkProgressTracker]
